//
//  ChessInfoArray.swift
//  Creator
//
//  Created by 吉乞悠 on 2019/10/22.
//  Copyright © 2019 吉乞悠. All rights reserved.
//

import Foundation

var ChessInfoArray: [[ChessInfo]] = [[Chapter1_chessInfo1,Chapter1_chessInfo2,Chapter1_chessInfo3],
                                     [Chapter2_chessInfo1,Chapter2_chessInfo2,Chapter2_chessInfo3],
                                     [Chapter3_chessInfo1,Chapter3_chessInfo2,Chapter3_chessInfo3]]

let Chapter1_chessInfo1 = ChessInfo(chessChapter: 1,
                                    chessBoardInfo: [[0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,9,1,1,4,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,2,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,2,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,2,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,2,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,6,1,1,1,1,1,8,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],],
                                    chessBoardAnswer: [(.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.turnDown, .Right),
                                                       (.vertical, .Down),
                                                       (.vertical, .Down),
                                                       (.vertical, .Down),
                                                       (.turnRight, .Down),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),],
                                    options: [.Left,.Right,.Down,.Up],
                                    programBlockNum: 2)

let Chapter1_chessInfo2 = ChessInfo(chessChapter: 1,
                                    chessBoardInfo: [[0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,9,1,4,0,3,1,4,0,0,0,0],
                                                     [0,0,0,0,2,0,2,0,2,0,0,0,0],
                                                     [0,0,0,0,2,0,2,0,2,0,0,0,0],
                                                     [0,0,0,0,2,0,2,0,2,0,0,0,0],
                                                     [0,0,0,0,2,0,2,0,2,0,0,0,0],
                                                     [0,0,0,0,6,1,5,0,6,1,1,8,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],],
                                    chessBoardAnswer: [(.horizen, .Right),
                                                       (.turnDown, .Right),
                                                       (.vertical, .Down),
                                                       (.vertical, .Down),
                                                       (.vertical, .Down),
                                                       (.turnRight, .Down),
                                                       (.turnUp, .Right),
                                                       (.vertical, .Up),
                                                       (.vertical, .Up),
                                                       (.vertical, .Up),
                                                       (.turnRight, .Up),
                                                       (.turnDown, .Right),
                                                       (.vertical, .Down),
                                                       (.vertical, .Down),
                                                       (.vertical, .Down),
                                                       (.turnRight, .Down),
                                                       (.horizen, .Right),],
                                    options: [.Left,.Right,.Down,.Up],
                                    programBlockNum: 6)

let Chapter1_chessInfo3 = ChessInfo(chessChapter: 1,
                                    chessBoardInfo: [[0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,3,1,1,1,4,0,0,0,0,0],
                                                     [0,0,0,2,0,0,0,2,0,0,0,0,0],
                                                     [0,0,0,2,0,0,0,2,0,0,0,0,0],
                                                     [0,9,1,5,0,0,0,2,0,0,0,0,0],
                                                     [0,0,0,0,0,3,1,5,0,0,0,0,0],
                                                     [0,0,0,0,0,2,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,6,1,1,1,1,1,8,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],],
                                    chessBoardAnswer: [(.horizen, .Right),
                                                       (.turnUp, .Right),
                                                       (.vertical, .Up),
                                                       (.turnRight, .Up),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.turnDown, .Right),
                                                       (.vertical, .Down),
                                                       (.vertical, .Down),
                                                       (.turnLeft, .Down),
                                                       (.turnDown, .Left),
                                                       (.turnRight, .Down),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),],
                                    options: [.Left,.Right,.Down,.Up],
                                    programBlockNum: 6)

let Chapter2_chessInfo2 = ChessInfo(chessChapter: 2,
                                    chessBoardInfo: [[0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,3,1,1,1,1,8,0],
                                                     [0,0,0,0,0,0,2,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,2,0,0,0,0,0,0],
                                                     [0,0,0,0,3,1,5,0,0,0,0,0,0],
                                                     [0,0,0,0,2,0,0,0,0,0,0,0,0],
                                                     [0,0,9,1,5,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],],
                                    chessBoardAnswer: [(.horizen, .Right),
                                                       (.turnUp, .Right),
                                                       (.turnRight, .Up),
                                                       (.turnUp, .Right),
                                                       (.vertical, .Up),
                                                       (.turnRight, .Up),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),],
                                    options: [.Left,.Right,.Down,.Up],
                                    programBlockNum: 4)

let Chapter2_chessInfo1 = ChessInfo(chessChapter: 2,
                                    chessBoardInfo: [[0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,3,1,1,1,1,1,8,0],
                                                     [0,0,0,0,0,2,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,2,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,2,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,2,0,0,0,0,0,0,0],
                                                     [0,0,9,1,1,5,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],],
                                    chessBoardAnswer: [(.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.turnUp, .Right),
                                                       (.vertical, .Up),
                                                       (.vertical, .Up),
                                                       (.vertical, .Up),
                                                       (.turnRight, .Up),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),],
                                    options: [.Left,.Right,.Down,.Up],
                                    programBlockNum: 2)

let Chapter2_chessInfo3 = ChessInfo(chessChapter: 2,
                                    chessBoardInfo: [[0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,3,1,4,0,0,0,0,0],
                                                     [0,0,0,0,0,2,0,2,0,0,0,0,0],
                                                     [0,0,0,0,0,2,0,2,0,0,0,0,0],
                                                     [0,0,0,0,0,2,0,6,1,1,1,8,0],
                                                     [0,0,0,0,0,2,0,0,0,0,0,0,0],
                                                     [0,0,9,1,1,5,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],],
                                    chessBoardAnswer: [(.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.turnUp, .Right),
                                                       (.vertical, .Up),
                                                       (.vertical, .Up),
                                                       (.vertical, .Up),
                                                       (.turnRight, .Up),
                                                       (.turnDown, .Right),
                                                       (.vertical, .Down),
                                                       (.turnRight, .Down),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),],
                                    options: [.Left,.Right,.Down,.Up],
                                    programBlockNum: 4)

let Chapter3_chessInfo1 = ChessInfo(chessChapter: 3,
                                    chessBoardInfo: [[0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,7,1,1,1,1,8,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,9,1,1,1,7,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],],
                                    chessBoardAnswer: [(.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.cloud, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),],
                                    options: [.Left,.Right,.Down,.Up,.Cloud],
                                    programBlockNum: 1)

let Chapter3_chessInfo2 = ChessInfo(chessChapter: 3,
                                    chessBoardInfo: [[0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,7,1,4,0,0,0,0],
                                                     [0,0,9,1,4,0,0,0,2,0,0,0,0],
                                                     [0,0,0,0,2,0,0,0,2,0,0,0,0],
                                                     [0,0,0,0,2,0,0,0,2,0,0,0,0],
                                                     [0,0,0,0,2,0,0,0,2,0,0,0,0],
                                                     [0,0,0,0,6,1,7,0,6,1,1,8,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],],
                                    chessBoardAnswer: [(.horizen, .Right),
                                                       (.turnDown, .Right),
                                                       (.vertical, .Down),
                                                       (.vertical, .Down),
                                                       (.turnRight, .Down),
                                                       (.cloud, .Right),
                                                       (.horizen, .Right),
                                                       (.turnDown, .Right),
                                                       (.vertical, .Down),
                                                       (.vertical, .Down),
                                                       (.vertical, .Down),
                                                       (.turnRight, .Down),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),],
                                    options: [.Left,.Right,.Down,.Up,.Cloud],
                                    programBlockNum: 5)

let Chapter3_chessInfo3 = ChessInfo(chessChapter: 3,
                                    chessBoardInfo: [[0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,3,1,7,0,0,0,0,0,0],
                                                     [0,0,0,0,2,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,6,1,1,1,1,1,8,0,0],
                                                     [0,0,9,1,1,1,1,1,4,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,2,0,0,0,0],
                                                     [0,0,0,0,7,1,7,1,5,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],
                                                     [0,0,0,0,0,0,0,0,0,0,0,0,0],],
                                    chessBoardAnswer: [(.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.turnDown, .Right),
                                                       (.turnLeft, .Down),
                                                       (.cloud, .Right),
                                                       (.horizen, .Left),
                                                       (.turnDown, .Left),
                                                       (.turnRight, .Down),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),
                                                       (.horizen, .Right),],
                                    options: [.Left,.Right,.Down,.Up,.Cloud],
                                    programBlockNum: 5)

